name: "[feature request]"
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: enhancement
assignees: criskkky
body:
  - type: textarea
    attributes:
      label: Describe your idea
      description: Provide a detailed description of your feature request
      placeholder: "What would you like to see added to the project?"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Acceptance criteria
      description: Check all that apply
      options:
        - label: Should be easy to implement
        - label: Should improve performance
        - label: Should be useful for a wide audience
    validations:
      required: false
